#cloud-config

users:
 - name: yc-user
   groups: sudo
   shell: /bin/bash
   sudo: ['ALL=(ALL) NOPASSWD:ALL']
   ssh-authorized-keys:
     - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCsSiG/sKIu4Uzg9jF0z0/hM2XyO4V3SKaL0RxkFLDFtB9kuauIDqxShRyINYyAJUunyPG1SvN7SaNSZyAzLozFn+8zPvwsA6PxUXBMGw0ghUzijsPQzrse+9IIruSMAuzfhjtUqe/K7PzoXdZ4q0diBSE2vSOC3WVymRGU2Mr19FeNyD056EO05VkHeVkndPnFbMa2F7qPUA/BSqtkJA8+ZQu1cd0z3vT9EPC7iYjMcMnP9LIUOUi4F7Pu3gaWXMNhVL3h3wpjIYrVhpHT2iOY7KZkA8byd3lYxd3bD2mCWAymd2wNt+rxuaL1EupYmUmhL/EzvHI1dFWMSIMfDMrEWQmZnWpEjC3uTqS+RwlZLlu52QkVs62e++3V464D2X4wK5gW2GQIUiDbEguzS9GPobkrK5PekZlN3A7oqUPImiyFIdCf67M2cWu8mvE2OxTpl/M2HGguoWi3OUydbcOtDu1GJrLMj/snnOxQToW48jGNIYJ2ZcYYWxLHuEHgsZU= ksenia@weber
runcmd:
 - curl https://raw.githubusercontent.com/Otus-DevOps-2020-11/xeniaweber_infra/cloud-testapp/install_ruby.sh | bash
 - curl https://raw.githubusercontent.com/Otus-DevOps-2020-11/xeniaweber_infra/cloud-testapp/install_mongodb.sh | bash
 - curl https://raw.githubusercontent.com/Otus-DevOps-2020-11/xeniaweber_infra/cloud-testapp/deploy.sh | bash



 
